name: keleos
description: Optimisez la performance de votre officine
public: false
url: http://www.keleos.fr

menu:
  - Accueil:
      link: /
  - Qui sommes nous ?:
      link: /apropos
  - Conseils :
      link: /
      menu:
        - La Formation:
            link: /formation
        - Études:
            link: /etudes
        - Test de Lisibilité:
            link: /tests
        - Animation et Merchandising :
            link: /merchandising
  - Contact:
      link: /contact

footer:
  - Site réalisé par Kozea:
      link: http://kozea.fr/

project (git):
  path: keleos
  branch: master
